### ISSUE TITLE
RDP implementation library as a separate crate

### ISSUE THREAD

**Issue by dheater** [Devolutions/IronRDP#119]
I would like to use `IronRDP` as a library implementing the RDP protocol without also consuming the clients.

This would enable me to implement an independent client.

**Comment by dheater** [comment]
I am currently using `ironrdp = { path = "../../IronRDP" }`, but I would like to be able to publish this client and point to the IronRDP crate (once its updates are published).

**Comment by CBenoit** [comment]
Hi!

> I would like to use `IronRDP` as a library implementing the RDP protocol without also consuming the clients.

Could you clarify what you mean here? IronRDP is already [broke down into numerous crates](https://github.com/Devolutions/IronRDP#architecture-work-in-progress). I intend to push this further and reduce the number of non vital dependencies from foundational crates in the future.

> I am currently using `ironrdp = { path = "../../IronRDP" }`, but I would like to be able to publish this client and point to the IronRDP crate (once its updates are published).

There is some API design work remaining before we can publish the crates, but it will happen. I’m considering publish a few candidate releases soonish. Have you a deadline or something similar so maybe I can adjust to it?

**Comment by dheater** [comment]
> Could you clarify what you mean here? IronRDP is already [broke down into numerous crates](https://github.com/Devolutions/IronRDP#architecture-work-in-progress).

Ah I think I understand know from the architecture page. I think I want the `ironrdp` meta-crate.

I am writing a Tauri client (referencing the one that used to be in this repo), so I only want the "protocol" stuff and not the clients. 

I don't have any deadline. This is pretty much a "toy" project for now and I can continue referencing my local copy for development. 

Thanks!

**Comment by dheater** [comment]
i think what through me off is the layout of the workspace. Specifically that `lib` (the meta-crate) is not under `crates` but the components of lib and the clients are.  I was expecting something more like this: https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html

**Comment by CBenoit** [comment]
> i think what through me off is the layout of the workspace. Specifically that `lib` (the meta-crate) is not under `crates` but the components of lib and the clients are. I was expecting something more like this: https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html

I see… I agree the current layout is not the most obvious in practice. I’m actually thinking about moving everything under `crates` with the full crate name.

**Comment by CBenoit** [comment]
@dheater FYI, I tried to clarify things in this PR: https://github.com/Devolutions/IronRDP/pull/123

**Comment by dheater** [comment]
:+1:  Yes. That is clearer @CBenoit
