### ISSUE TITLE
Support KDC proxy URL injected in web client

### ISSUE THREAD

**Issue by awakecoding** [Devolutions/IronRDP#155]
In order to support Kerberos in the IronRDP web client, we need a proper build with the sspi-rsnetwork_client feature enabled. KDC detection is not required, since we'll inject a KDC proxy URL (https) into IronRDP, and we need a way to pass it down to sspi-rs through the Rust APIs to be used properly. Once we have this, web-based, RDP connections through the Devolutions Gateway should be able to use Kerberos properly.

Draft PR enabling the missing features: https://github.com/Devolutions/IronRDP/pull/154

If reqwest is a problem for in-browser blocking HTTP calls, the new [ehttp crate](https://github.com/emilk/ehttp) can be used instead.

**Comment by CBenoit** [comment]
Draft in IronRDP (#154) is requiring some API modification on sspi-rs side. See [FIXME comments](https://github.com/Devolutions/IronRDP/blob/1e7030e0af63f672051ff940007cb2e019e94c68/crates/ironrdp-web/src/network_client.rs#L26).

> NetworkClient trait should provide another method to advertise available network methods (in our case, only HTTP is supported)

>  NetworClient::send_http method should be updated so that implementer don’t need to re-implement the ASN.1 DER encoding / decoding dance himself (this logic can be extracted in sspi-rs itself)
