### ISSUE TITLE
RDP server

### ISSUE THREAD

**Issue by xiaoquanju** [Devolutions/IronRDP#49]

**Comment by awakecoding** [comment]
No fully-functional IronRDP server has been developed at this point, the closest would be a lightweight RDP proxy that inspects the packets without touching them. If you wish to start building an IronRDP server, we would welcome such contributions, as improvements to the core library would be required.

**Comment by elmarco** [comment]
@awakecoding fyi, I have submitted a related project idea for QEMU outreach/SoC: https://wiki.qemu.org/Internships/ProjectIdeas/RDPServer

**Comment by awakecoding** [comment]
> @awakecoding fyi, I have submitted a related project idea for QEMU outreach/SoC: https://wiki.qemu.org/Internships/ProjectIdeas/RDPServer

that sounds like an exciting project! A FreeRDP server would be a lot easier, but I would really like to have someone build a first IronRDP server instead. I wasn't aware that QEMU exposed an out-of-process dbus interface now - years ago I worked on a contract for a company that made their own out-of-process RDP server using FreeRDP. If I can give on tip for a server: start with RDP 7.1 RemoteFX. The codec itself isn't the simplest, but it's the best way to get complete desktop images without mixing them with RDP6 GDI messages or the RDP8 graphics pipeline that mixes a bunch of codecs together.

**Comment by elmarco** [comment]
@awakecoding yes, I imagined it would be a lot easier to do it with freerdp (perhaps even too easy for the basic display/input). I must say I am still not familiar enough with RDP (and even less IronDRP) to know how much work is needed and where to start. Would you like to co-mentor the project? Or could you sketch a bit the required work with some reference pointers? thanks

[btw, with the recent code example, it looks like I could use IronRDP for the [RDW/Gtk](https://gitlab.gnome.org/malureau/rdw) client now, as an alternative to freerdp - I should give it a try]

**Comment by CBenoit** [comment]
@mihneabuz opened a PR to add support for this: https://github.com/Devolutions/IronRDP/pull/167 :tada:

**Comment by elmarco** [comment]
this issue should be closed now
