### ISSUE TITLE
How can I check RDP credentials? (without massive overhead)

### ISSUE THREAD

**Issue by fu3x11** [Devolutions/IronRDP#508]
I am trying to integrate something in my application that checks the existing ip, username, password and optionally domain, to see if its connectable or not. right now it takes 1700 milliseconds which is way too slow. what can i do to achieve this in the most lightweight way possible? i kinda just need to start the nla and get a result. possibly using low level functions

```rust
use anyhow::Context as _;
use ironrdp::{
    connector::{
        self,
        credssp::{CredsspProcessGenerator, CredsspSequence, KerberosConfig},
        custom_err,
        sspi::{credssp::ClientState, generator::GeneratorState},
        ClientConnector, ConnectionResult, ConnectorError, ConnectorErrorKind, ConnectorResult,
        Credentials, ServerName,
    },
    pdu::{
        gcc::KeyboardType,
        rdp::{capability_sets::MajorPlatformType, client_info::PerformanceFlags},
        write_buf::WriteBuf,
    },
};
use ironrdp_tls::upgrade;
use ironrdp_tokio::{AsyncNetworkClient, Framed, FramedRead, FramedWrite, Upgraded};
use tokio::net::TcpStream;

use crate::network_client::ReqwestNetworkClient;

pub async fn run(
    server_name: String,
    port: u16,
    username: String,
    password: String,
    domain: Option<String>,
) -> anyhow::Result<()> {
    let config = build_config(username, password, domain);

    connect(config, server_name, port)
        .await
        .context("connect")?;

    Ok(())
}

async fn connect(config: connector::Config, server_name: String, port: u16) -> anyhow::Result<()> {
    let server_addr = lookup_addr(&server_name, port).context("lookup addr")?;

    let tcp_stream = TcpStream::connect(server_addr)
        .await
        .context("TCP connect")?;

    let mut framed: ironrdp_tokio::Framed<ironrdp_tokio::TokioStream<TcpStream>> =
        ironrdp_tokio::Framed::new(tcp_stream);

    let mut connector = connector::ClientConnector::new(config).with_server_addr(server_addr);

    let should_upgrade = ironrdp_tokio::connect_begin(&mut framed, &mut connector)
        .await
        .context("begin connection")?;

    let initial_stream = framed.into_inner_no_leftover();

    let (upgraded_stream, server_public_key) = upgrade(initial_stream, &server_name)
        .await
        .context("TLS upgrade")?;

    let upgraded = ironrdp_tokio::mark_as_upgraded(should_upgrade, &mut connector);

    let mut upgraded_framed: ironrdp_tokio::Framed<ironrdp_tokio::TokioStream<_>> =
        ironrdp_tokio::Framed::new(upgraded_stream);

    let network_client: &mut dyn AsyncNetworkClient = &mut ReqwestNetworkClient::new();

    ironrdp_tokio::connect_finalize(
        upgraded,
        &mut upgraded_framed,
        connector,
        server_name.into(),
        server_public_key,
        Some(network_client),
        None,
    )
    .await
    .context("finalize connection")?;

    Ok(())
}

fn lookup_addr(hostname: &str, port: u16) -> anyhow::Result<std::net::SocketAddr> {
    use std::net::ToSocketAddrs as _;
    let addr = (hostname, port).to_socket_addrs()?.next().unwrap();
    Ok(addr)
}

fn build_config(username: String, password: String, domain: Option<String>) -> connector::Config {
    connector::Config {
        credentials: Credentials::UsernamePassword { username, password },
        domain,
        enable_tls: false, // This example does not expose any frontend.
        enable_credssp: true,
        keyboard_type: KeyboardType::IbmEnhanced,
        keyboard_subtype: 0,
        keyboard_layout: 0,
        keyboard_functional_keys_count: 12,
        ime_file_name: String::new(),
        dig_product_id: String::new(),
        desktop_size: connector::DesktopSize {
            width: 1280,
            height: 1024,
        },
        bitmap: None,
        client_build: 0,
        client_name: "ironrdp-screenshot-example".to_owned(),
        client_dir: "C:\\Windows\\System32\\mstscax.dll".to_owned(),

        #[cfg(windows)]
        platform: MajorPlatformType::WINDOWS,
        #[cfg(target_os = "macos")]
        platform: MajorPlatformType::MACINTOSH,
        #[cfg(target_os = "ios")]
        platform: MajorPlatformType::IOS,
        #[cfg(target_os = "linux")]
        platform: MajorPlatformType::UNIX,
        #[cfg(target_os = "android")]
        platform: MajorPlatformType::ANDROID,
        #[cfg(target_os = "freebsd")]
        platform: MajorPlatformType::UNIX,
        #[cfg(target_os = "dragonfly")]
        platform: MajorPlatformType::UNIX,
        #[cfg(target_os = "openbsd")]
        platform: MajorPlatformType::UNIX,
        #[cfg(target_os = "netbsd")]
        platform: MajorPlatformType::UNIX,

        no_server_pointer: true,
        autologon: false,
        pointer_software_rendering: true,
        performance_flags: PerformanceFlags::default(),
        desktop_scale_factor: 0,
    }
}

**Comment by CBenoit** [comment]
You could stop after performing the NLA (via CredSSP). It’s inside the `connect_finalize` function:

https://github.com/Devolutions/IronRDP/blob/9410f5356b25d2eecc2cee1aed0804ecca4cf3f6/crates/ironrdp-async/src/connector.rs#L62-L73

You don’t need to complete the full sequence coming afterwards. You can see how we instrument the connector in the same file.

You’ll still have a few network round-trips before that, including:

- Connection Initiation Exchange
- TLS upgrade
- NLA

Fortunately, when using enhanced RDP security, even the basic settings exchange is performed _after_ authentication, so you should get a massive improvement.

**Comment by fu3x11** [comment]
> You could stop after performing the NLA (via CredSSP). It’s inside the `connect_finalize` function:
> 
> 
> 
> https://github.com/Devolutions/IronRDP/blob/9410f5356b25d2eecc2cee1aed0804ecca4cf3f6/crates/ironrdp-async/src/connector.rs#L62-L73
> 
> 
> 
> You don’t need to complete the full sequence coming afterwards. You can see how we instrument the connector in the same file.
> 
> 
> 
> You’ll still have a few network round-trips before that, including:
> 
> 
> 
> - Connection Initiation Exchange
> 
> - TLS upgrade
> 
> - NLA
> 
> 
> 
> Fortunately, when using enhanced RDP security, even the basic settings exchange is performed _after_ authentication, so you should get a massive improvement.

so comment this out and return Ok(()) instead of Ok(result)?
```rust
let result = loop {
        single_sequence_step(framed, &mut connector, &mut buf).await?;

        if let ClientConnectorState::Connected { result } = connector.state {
            break result;
        }
    };

    info!("Connected with success");

**Comment by CBenoit** [comment]
Yeah, you could do that.

**Comment by fu3x11** [comment]
> Yeah, you could do that.

anything else to point out?

**Comment by CBenoit** [comment]
You could probably look more deeply into CredSSP (and our [sspi](https://github.com/Devolutions/sspi-rs) crate), but nothing else I can add without digging further myself at this point.

**Comment by fu3x11** [comment]
> [FreeRDP](https://github.com/FreeRDP/FreeRDP) has an `auth-only` command-line switch which does the same thing you are trying to achieve. You might investigate their code base and see what optimizations are made in this case, and if the same can be applied to IronRDP. You could also see how long the authentication takes in that case as a comparison baseline.

i got mine to 700 ms so far, and it needs to be tokio

**Comment by fu3x11** [comment]
> You could probably look more deeply into CredSSP (and our [sspi](https://github.com/Devolutions/sspi-rs) crate), but nothing else I can add without digging further myself at this point.

could i also just return 
`generator
                    .resolve_to_result()
                    .map_err(|e| custom_err!("resolve without network client", e))?
from the else statement instead of doing if else and resolve without the network client? is it needed?

```rust
let client_state = {
            let mut generator = sequence.process_ts_request(ts_request);

            if let Some(network_client_ref) = network_client.as_deref_mut() {
                resolve_generator(&mut generator, network_client_ref).await?
            } else {
                generator
                    .resolve_to_result()
                    .map_err(|e| custom_err!("resolve without network client", e))?
            }
        }; // drop generator

**Comment by fu3x11** [comment]
@CBenoit

**Comment by CBenoit** [comment]
@fu3x11 Please give us some time before sending a reminder, I didn't get a chance to go through all my notifications, and it was weekend. If you are worried about me not having a notification, don't worry, all people participating to the issue will be notified when a new message is posted unless they decide ti manually disable them 🙂

For your question, I depends on what you need. You don't need HTTP requests if you're only going to rely on NTLM. However, NTLM is deprecated by Microsoft and should not be used whenever possible. You may be able to use it safely under specific circumstances, and I'm pretty sure you'll always be able to enable it because Microsoft does not remove features. If you want to support Kerberos, then you need to perform HTTP requests. You may replace the HTTP client by something more lightweight if you don't want reqwest in your dependency tree, but I'm not sure you can make things much faster with that.

**Comment by fu3x11** [comment]
> @fu3x11 Please give us some time before sending a reminder, I didn't get a chance to go through all my notifications, and it was weekend. If you are worried about me not having a notification, don't worry, all people participating to the issue will be notified when a new message is posted unless they decide to manually disable them 🙂
> 
> For your question, I depends on what you need. You don't need the network client if you're only going to rely on NTLM. However, NTLM is deprecated by Microsoft and should not be used whenever possible. You may be able to use it safely under specific circumstances, and I'm pretty sure you'll always be able to enable it because Microsoft does not remove features. If you want to support Kerberos, then you need to perform these network requests. You may replace the HTTP client by something more lightweight if you don't want reqwest in your dependency tree, but I'm not sure you can make things much faster with that.

so nltm can connect to any and every server?

**Comment by thenextman** [comment]
Also, it's not only policy that requires kerberos. For example, if a user is a member of "Protected Users" group in Active Directory and NLA us used, kerberos is required.

**Comment by fu3x11** [comment]
> You can’t connect to servers where Kerberos is enforced (there is a Windows Group Policy). If you have control over the servers, you may decide to allow NTLM probably forever. Not saying that you should, NTLM is deprecated for security reasons.

yeah the issue im having is your guy's async network client doesn't implement send, could i easily add that in my local copy of async network client or is it more complicated than that

**Comment by CBenoit** [comment]
We can likely add `Send` bounds at more places to help you with that. I’m guessing you are having trouble with spawning stuff in tokio runtime? Can you send a sample of your code so I can see more clearly what you are trying to achieve? IronRDP crates are currently used at many places, including on server-side by [teleport](https://github.com/gravitational/teleport). IIRC, they already suggested adding a few `Send` bounds at some places so things should be mostly straightforward, but maybe we need to add some more? Things may not be so simple because we also need to implement specific traits for non-`Send` types in the WASM client. In their case, we got around by providing both a `Send` and a non-`Send` option (`TokioFramed` vs `LocalTokioFramed`).

**Comment by fu3x11** [comment]
> We can likely add `Send` bounds at more places to help you with that. I’m guessing you are having trouble with spawning stuff in tokio runtime? Can you send a sample of your code so I can see more clearly what you are trying to achieve? IronRDP crates are currently used at many places, including on server-side by [teleport](https://github.com/gravitational/teleport). IIRC, they already suggested adding a few `Send` bounds at some places so they could spawn more tasks, and I expect things to be mostly straightforward, but maybe we need to add some more? Things may not be so simple because we also need to implement specific traits for non-`Send` types in the WASM client. In their case, we got around by providing both a `Send` and a non-`Send` option (`TokioFramed` vs `LocalTokioFramed`).

Hello, i am doing fine and all my testing past, what could possibly help are examples of async+sync auth checkers meant for returning a result signifying that the server is connectable or not, (headless, in a lightweight manner). which i have done already 

but for future reference and ease of use for everyone else, possibly putting send and other examples would make things more swift in applying this library to other projects

**Comment by fu3x11** [comment]
by chance could this stuff be on crates.io, along with lower level functionality so you don't have to go in and modify the crates?

in my experience i had to download the tokio iron rdp and async iron rdp and edit them to my liking

**Comment by CBenoit** [comment]
> Hello, i am doing fine and all my testing passes,

Glad you could make it.

> what could possibly help are examples of async+sync auth checkers meant for returning a result signifying that the server is connectable or not, (headless, in a lightweight manner). which i have done already
> 
> but for future reference and ease of use for everyone else, possibly putting send and other examples would make things more swift in applying this library to other projects

Thank you for the feedback. Feel free to send PRs for adding documentation and examples. We are not selling and getting money by making IronRDP open source and free. We are actively working on it, but bandwidth is limited, so any help is welcomed, including for the documentation effort.

As for adding `Send`, as said here above,

> Things may not be so simple because we also need to implement specific traits for non-`Send` types in the WASM client. In their case, we got around by providing both a `Send` and a non-`Send` option (`TokioFramed` vs `LocalTokioFramed`).

Again, maybe you could open a PR so we can see what can be done. Our CI will also catch if the WASM client is not compiling anymore.

> by chance could this stuff be on crates.io, along with lower level functionality so you don't have to go in and modify the crates?
> 
> in my experience i had to download the tokio iron rdp and async iron rdp and edit them to my liking

There is another issue related to this question: https://github.com/Devolutions/IronRDP/issues/498
Crates will be published on crates.io in the future. I would like to get that done within one month or two ideally.

I’ll close this issue since the question appears to be answered.
