### ISSUE TITLE
Confused - I need to verify credentials on an RDP

### ISSUE THREAD

**Issue by slezercc** [Devolutions/IronRDP#538]
Hello, I am having to verify credentials on my RDP quickly in a scalable way. Can anyone possibly provide a code snippet? I only need to verify if a set of credentials is valid, it's all I need really.

**Comment by CBenoit** [comment]
I don’t have any code snippet at hand, but someone already asked the same question in the past: https://github.com/Devolutions/IronRDP/issues/508
I have no idea why, but they decided to delete all their messages and change the issue title with something unhelpful… You can still see my answers though.
Just in case, I’ll try poking the original poster as well.
cc @leyloe

**Comment by slezercc** [comment]
> I don’t have any code snippet at hand, but someone already asked the same question in the past: #508 I have no idea why, but they decided to delete all their messages and changed the issue title to something unhelpful… You can still see my answers though. Just in case, I’ll try poking the original poster as well. cc @leyloe

Thank you for the super fast answer. I saw you guys have a matrix channel, perhaps I would have luck asking in there? What do you think? I don't really feel like downloading the ironrdp stack and modifying a whole lot unless I realize it is needed for optimal performance.

**Comment by awakecoding** [comment]
I get the feeling that your intended use case is RDP brute forcing, and you're pretty much asking for us to do help you make it work with minimal effort on your side. While we cannot prevent you from trying to optimize IronRDP for such use cases, brute forcing of RDP is a non-goal of this project, so I'm closing the issue.

**Comment by slezercc** [comment]
I'm only having to check a single set of credentials, I find it curious that I get accused of that while someone asked the same question as me and received some help :/

**Comment by leyloe** [comment]
> I don’t have any code snippet at hand, but someone already asked the same question in the past: https://github.com/Devolutions/IronRDP/issues/508
> 
> I have no idea why, but they decided to delete all their messages and changed the issue title to something unhelpful… You can still see my answers though.
> 
> Just in case, I’ll try poking the original poster as well.
> 
> cc @leyloe

slezer messaged me, with the intent of creating a RDP bruteforcer and he wanted my codebase responsible for checking credentials.

the project related to this is for educational purposes, and i will open source the project later on.

but this person is planning on using it for malicious intent so ill give it a few years for rdp bruting to die down a bit
