### ISSUE TITLE
Error occurred after refactor(pdu)

### ISSUE THREAD

**Issue by lidarbtc** [Devolutions/IronRDP#541]
I change screenshot example config little bit.

```rust
enable_tls: true,
enable_credssp: false,
```

and I run `cargo run --example=screenshot -- --host 127.0.0.1 --username 1 --password 2 --output out.bmp`

I got this error.

```
Error: connect

Caused by:
    0: finalize connection
    1: [decode error] decode error
    2: [SendDataIndication] invalid `domain-mcspdu`: unexpected application tag for CHOICE
```

But when I run the `git checkout 703b245993f5af096734b273436bf47ac1f939d1` command after it, it works fine.

Maybe there are wrong changes between 402ffd56c93af5a5e8578fc241071a64840b785d and fb8f12a62e7778e41d92db3f032f40d4efd953b4.

**Comment by CBenoit** [comment]
Hello @lidarbtc 
Good catch, thank you for reporting this bug.
It has been fixed in #543
